channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - configparser
  - graphviz
  - black
  - python
  - matplotlib
  - ipympl
  - seaborn>=0.13
  - gdal
  - pandas
  - geopandas
  - libpysal
  - esda
  - splot
  - spreg
  - spglm
  - access
  - mgwr
  - mapclassify
  - statsmodels
  - spectra
  - descartes
  - scikit-learn<1.6
  - wordcloud
  - pip
  - graph-tool
  - cytoolz
  - jupyter
  - ipykernel
  - gensim
  - python-rapidjson
  - umap-learn
  - hdbscan
  - shapely
  - numpy
  - cython
  - pygeos
  - h3-py
  - contextily
  - sphinx
  - spacy
  - dask
  - tqdm
  - future
  - pyrosm==0.6.2
  - r5py
  - python-ternary
  - python-dotenv
  - scipy<1.13
  - py-xgboost-gpu 
  - shap
  - pytorch
  - pytorch-cuda
  - regex
  - nltk
  - pip:
    - bezier
    - scattertext
    - adjustText
    - matplotlib-scalebar
    - pymunk
    - xlrd
    - flashtext
    - alphashape
    - s2sphere
    - lxml
    - sphinx-basic-ng
    - furo
    - pyreadstat
    - KDEpy
    - formulaic
    - interface_meta
    - pysentimiento
