channels:
  - conda-forge
dependencies:
  - configparser
  - graphviz
  - black
  - python>=3.8
  - matplotlib=3.7.1
  - ipympl
  - seaborn
  - gdal
  - pandas
  - geopandas<=0.9.0
  - libpysal
  - esda
  - splot
  - spreg
  - spglm
  - mgwr
  - mapclassify
  - statsmodels
  - networkx
  - spectra
  - descartes
  - scikit-learn<=1.2.2
  - wordcloud
  - pip
  - graph-tool
  - cytoolz
  - jupyter
  - ipykernel
  - gensim
  - python-rapidjson
  - umap-learn
  - hdbscan<=0.8.29
  - shapely<=1.7.1
  - numpy<=1.22.4
  - cython<=0.29.28
  - pygeos<=0.10
  - h3-py==3.7.4
  - contextily
  - sphinx
  - spacy
  - dask
  - tqdm
  - future
  - pip:
    - bezier
    - scattertext
    - adjustText
    - matplotlib-scalebar
    - git+https://github.com/zorzalerrante/scikit-fusion
    - pymunk
    - emoji
    - xlrd
    - shifterator
    - flashtext
    - alphashape
    - s2sphere
    - pyrosm==0.6.1
    - cykhash==2.0.1
    - lxml
    - pyreadstat
    - pyrobuf
    - KDEpy
    - pydata-sphinx-theme