channels:
  - conda-forge
dependencies:
  - configparser==5.3.0
  - graphviz==7.0.5
  - black
  - python<=3.9.18
  - matplotlib==3.7.1
  - ipympl
  - seaborn==0.12.2
  - gdal==3.6.0
  - pandas==2.0.3
  - geopandas==0.13.2
  - libpysal==4.7.0
  - esda==2.5.0
  - splot==1.1.5.post1
  - spreg==1.3.2
  - spglm==1.0.8
  - mgwr==2.1.2
  - mapclassify==2.5.0
  - statsmodels==0.14.0
  - spectra
  - descartes==1.1.0
  - scikit-learn<=1.2.2
  - wordcloud
  - pip
  - graph-tool
  - cytoolz
  - jupyter
  - ipykernel
  - gensim
  - python-rapidjson
  - umap-learn
  - hdbscan<=0.8.29
  - shapely<=1.8.2
  - numpy<=1.22.4
  - cython<=0.29.28
  - pygeos<=0.12
  - h3-py==3.7.4
  - contextily
  - sphinx
  - spacy
  - dask
  - tqdm
  - future
  - pip:
    - Jinja2
    - bezier==2023.7.28
    - scattertext==0.1.19
    - adjustText==0.8
    - matplotlib-scalebar==0.8.1
    - git+https://github.com/zorzalerrante/scikit-fusion
    - pymunk==6.5.1
    - emoji==2.8.0
    - xlrd==2.0.1
    - shifterator==0.3.0
    - flashtext==2.7
    - alphashape==1.3.1
    - s2sphere==0.2.5
    - pyrosm==0.6.1
    - cykhash==2.0.1
    - lxml==4.9.3
    - sphinx-rtd-theme
    - pyreadstat==1.2.3
    - pyrobuf==0.9.3
    - KDEpy==1.1.5
