channels:
  - conda-forge
dependencies:
  - configparser
  - graphviz
  - black
  - python
  - matplotlib
  - ipympl
  - seaborn
  - gdal
  - pandas
  - geopandas
  - libpysal<4.8.0
  - esda
  - splot
  - spreg
  - spglm
  - access
  - mgwr
  - mapclassify
  - statsmodels
  - spectra
  - descartes
  - scikit-learn
  - wordcloud
  - pip
  - graph-tool
  - cytoolz
  - jupyter
  - ipykernel
  - gensim
  - python-rapidjson
  - umap-learn
  - hdbscan
  - shapely
  - numpy
  - cython
  - pygeos
  - h3-py
  - contextily
  - sphinx
  - spacy
  - dask
  - tqdm
  - future
  - pyrosm==0.6.2
  - r5py
  - python-ternary
  - python-dotenv
  - pip:
    - bezier
    - scattertext
    - adjustText
    - matplotlib-scalebar
    - git+https://github.com/zorzalerrante/scikit-fusion
    - pymunk
    - emoji
    - xlrd
    - shifterator
    - flashtext
    - alphashape
    - s2sphere
    - lxml
    - sphinx-basic-ng
    - furo
    - pyreadstat
    - KDEpy
